name: Run Tests

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test