name: Run Tests

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2  # This step is necessary to access your repository's files

    - name: Set node js version
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test