name: Run Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-test-workflow:
    uses: ./.github/actions/module-test@polishing
    with:
      node-version: '20'
