name: Run Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: housten/ToDoApp/.github/workflows/module-test.yaml@main
    with:
      node-version: '20'
